from pydantic import BaseModel, Field, model_validator
from typing import Any, Dict, List


class AnalyzeRequest(BaseModel):
    image_path: str = Field(
        ...,
        min_length=1,
        max_length=500,
        description="Firebase Storage image path",
        examples=[
            "satellite_images/user123/image_001.png"
        ],
    )

    query: str = Field(
        ...,
        min_length=1,
        max_length=2000,
        description="Question or instructions for image analysis",
        examples=[
            "Analyze this satellite image and "
            "describe the visible buildings."
        ],
    )

    max_new_tokens: int = Field(
        default=256,
        ge=16,
        le=2048,
        description="Maximum number of tokens generated by Qwen",
    )

    image_paths: List[str] | None = Field(
        default=None,
        min_length=1,
        max_length=4,
        description="Optional ordered Firebase Storage paths for multi-image Qwen analysis",
    )

    # Deprecated compatibility field. Production grouping is always derived
    # from trusted Firebase Storage metadata, never from browser JSON.
    manifest: Dict[str, Any] | None = None

    @model_validator(mode="after")
    def validate_image_inputs(self) -> "AnalyzeRequest":
        paths = self.image_paths or [self.image_path]
        if not 1 <= len(paths) <= 4:
            raise ValueError("between one and four image paths are supported")
        if any(not path.strip() for path in paths):
            raise ValueError("image paths must not be empty")
        return self


class AnalyzeResponse(BaseModel):
    answer: str = Field(
        ...,
        description="AI-generated satellite image analysis",
    )


class StatusResponse(BaseModel):
    status: str
    version: str = "1.0.0"
    qwen_configured: bool
    firebase_configured: bool


class RegisterRequest(BaseModel):
    email: str
    password: str = Field(
        ...,
        min_length=6,
        max_length=128,
    )


class LoginRequest(BaseModel):
    email: str
    password: str = Field(
        ...,
        min_length=6,
        max_length=128,
    )


class TokenResponse(BaseModel):
    access_token: str
    token_type: str = "bearer"


class UserResponse(BaseModel):
    id: str
    email: str
