from pydantic import BaseModel, Field


class AnalyzeRequest(BaseModel):
    image_path: str = Field(
        ...,
        min_length=1,
        max_length=500,
        description="Firebase Storage image path",
        examples=[
            "satellite_images/user123/image_001.png"
        ],
    )

    query: str = Field(
        ...,
        min_length=1,
        max_length=2000,
        description="Question or instructions for image analysis",
        examples=[
            "Analyze this satellite image and "
            "describe the visible buildings."
        ],
    )

    max_new_tokens: int = Field(
        default=256,
        ge=16,
        le=2048,
        description="Maximum number of tokens generated by Qwen",
    )


class AnalyzeResponse(BaseModel):
    answer: str = Field(
        ...,
        description="AI-generated satellite image analysis",
    )


class StatusResponse(BaseModel):
    status: str
    version: str = "1.0.0"
    qwen_configured: bool
    firebase_configured: bool


class RegisterRequest(BaseModel):
    email: str
    password: str = Field(
        ...,
        min_length=6,
        max_length=128,
    )


class LoginRequest(BaseModel):
    email: str
    password: str = Field(
        ...,
        min_length=6,
        max_length=128,
    )


class TokenResponse(BaseModel):
    access_token: str
    token_type: str = "bearer"


class UserResponse(BaseModel):
    id: str
    email: str