from pydantic import BaseModel, Field, model_validator
from typing import Any, Dict, List, Optional


class AnalyzeRequest(BaseModel):
    image_path: str = Field(
        ...,
        min_length=1,
        max_length=500,
        description="S3 object key for the primary satellite image",
        examples=["users/user123/imagery/abc123/image_001.png"],
    )

    query: str = Field(
        ...,
        min_length=1,
        max_length=2000,
        description="Question or instructions for image analysis",
        examples=["Analyze this satellite image and describe the visible buildings."],
    )

    max_new_tokens: int = Field(
        default=256,
        ge=16,
        le=2048,
        description="Maximum number of tokens generated by Qwen",
    )

    image_paths: Optional[List[str]] = Field(
        default=None,
        description="Optional ordered S3 object keys for multi-image Qwen analysis",
    )

    # The browser supplies logical observation grouping; the API binds its
    # physical references to S3-verified transport metadata before use.
    input_manifest: Optional[Dict[str, Any]] = None

    # Aligned physical-file hints used while constructing the trusted S3
    # records. S3 remains authoritative for object identity, type, and size.
    image_metadata: Optional[List[Dict[str, Any]]] = None

    # Deprecated compatibility field retained for older clients.
    manifest: Optional[Dict[str, Any]] = None

    @model_validator(mode="after")
    def validate_image_inputs(self) -> "AnalyzeRequest":
        paths = self.image_paths or [self.image_path]
        if not 1 <= len(paths) <= 4:
            raise ValueError("between one and four image paths are supported")
        if any(not path.strip() for path in paths):
            raise ValueError("image paths must not be empty")
        return self


class AnalyzeResponse(BaseModel):
    answer: str = Field(
        ...,
        description="AI-generated satellite image analysis",
    )


class StatusResponse(BaseModel):
    status: str
    version: str = "1.0.0"
    qwen_configured: bool
    aws_configured: bool
