import logging
from unittest.mock import MagicMock, patch
import pytest
from fastapi.testclient import TestClient

from main import app
from config import Settings
from services.firebase_service import FirebaseStorageService, get_storage_service
from services.qwen_service import QwenService, get_qwen_service
from api.routes import get_current_user

client = TestClient(app)

TEST_USER_ID = "user123"
OTHER_USER_ID = "user456"
VALID_IMAGE_PATH = f"satellite_images/{TEST_USER_ID}/image_001.png"
UNAUTHORIZED_IMAGE_PATH = f"satellite_images/{OTHER_USER_ID}/image_001.png"
SAMPLE_SIGNED_URL = "https://storage.googleapis.com/akasha-v1.appspot.com/secret-token-uuid-12345"


@pytest.fixture
def mock_user():
    return {"uid": TEST_USER_ID, "email": "test@example.com"}


@pytest.fixture
def mock_storage():
    storage = MagicMock(spec=FirebaseStorageService)
    # Default validate_image_path behavior
    storage.validate_image_path.side_effect = lambda p: p.strip().replace("\\", "/")

    # Default verify_user_authorization: pass if user_id in path, else raise 403
    def verify_auth(user_id, image_path):
        parts = image_path.strip("/").split("/")
        if len(parts) >= 2 and parts[1] != user_id:
            from fastapi import HTTPException
            raise HTTPException(status_code=403, detail="Access denied")

    storage.verify_user_authorization.side_effect = verify_auth
    storage.generate_signed_url.return_value = SAMPLE_SIGNED_URL
    return storage


@pytest.fixture
def mock_qwen():
    qwen = MagicMock(spec=QwenService)
    qwen.analyze.return_value = "Detailed satellite analysis: 5 residential buildings detected."
    return qwen


# ---------------------------------------------------------------------------
# 1. Authorized image -> signed URL -> Qwen call -> answer returned
# ---------------------------------------------------------------------------
def test_authorized_image_analysis_success(mock_user, mock_storage, mock_qwen):
    app.dependency_overrides[get_current_user] = lambda: mock_user
    app.dependency_overrides[get_storage_service] = lambda: mock_storage
    app.dependency_overrides[get_qwen_service] = lambda: mock_qwen

    try:
        response = client.post(
            "/api/analyze",
            json={
                "image_path": VALID_IMAGE_PATH,
                "query": "Analyze this satellite image.",
                "max_new_tokens": 256,
            },
            headers={"Authorization": "Bearer valid-mock-token"},
        )

        assert response.status_code == 200
        data = response.json()
        assert "answer" in data
        assert data["answer"] == "Detailed satellite analysis: 5 residential buildings detected."

        # Verify Qwen was called with the signed URL generated by the storage service
        mock_storage.generate_signed_url.assert_called_once_with(VALID_IMAGE_PATH)
        mock_qwen.analyze.assert_called_once_with(
            user_message="Analyze this satellite image.",
            image_url=SAMPLE_SIGNED_URL,
            max_new_tokens=256,
        )
    finally:
        app.dependency_overrides.clear()


# ---------------------------------------------------------------------------
# 2. Unauthorized image -> 403 Forbidden
# ---------------------------------------------------------------------------
def test_unauthorized_image_returns_403(mock_user, mock_storage, mock_qwen):
    app.dependency_overrides[get_current_user] = lambda: mock_user
    app.dependency_overrides[get_storage_service] = lambda: mock_storage
    app.dependency_overrides[get_qwen_service] = lambda: mock_qwen

    try:
        response = client.post(
            "/api/analyze",
            json={
                "image_path": UNAUTHORIZED_IMAGE_PATH,
                "query": "Analyze unauthorized image",
            },
            headers={"Authorization": "Bearer valid-mock-token"},
        )

        assert response.status_code == 403
        assert "Access denied" in response.json()["detail"]
        # Storage URL generation and Qwen analysis should NOT be reached
        mock_storage.generate_signed_url.assert_not_called()
        mock_qwen.analyze.assert_not_called()
    finally:
        app.dependency_overrides.clear()

def test_invalid_firebase_token_is_rejected():
    from services.firebase_service import verify_firebase_token
    from fastapi import HTTPException

    with pytest.raises(HTTPException) as exc_info:
        verify_firebase_token("invalid-firebase-token")

    assert exc_info.value.status_code == 401
# ---------------------------------------------------------------------------
# 3. Missing image in storage -> 404 Not Found
# ---------------------------------------------------------------------------
def test_missing_image_returns_404(mock_user, mock_storage, mock_qwen):
    from fastapi import HTTPException
    mock_storage.generate_signed_url.side_effect = HTTPException(
        status_code=404, detail="The requested image object was not found in storage"
    )

    app.dependency_overrides[get_current_user] = lambda: mock_user
    app.dependency_overrides[get_storage_service] = lambda: mock_storage
    app.dependency_overrides[get_qwen_service] = lambda: mock_qwen

    try:
        response = client.post(
            "/api/analyze",
            json={
                "image_path": VALID_IMAGE_PATH,
                "query": "Analyze missing image",
            },
            headers={"Authorization": "Bearer valid-mock-token"},
        )

        assert response.status_code == 404
        assert "not found" in response.json()["detail"].lower()
        mock_qwen.analyze.assert_not_called()
    finally:
        app.dependency_overrides.clear()


# ---------------------------------------------------------------------------
# 4. Missing HF_TOKEN -> 500 configuration error
# ---------------------------------------------------------------------------
def test_missing_hf_token_returns_500(mock_user, mock_storage):
    # Use actual QwenService with empty token
    qwen_service_no_token = QwenService(space="AdityaSingh1531/qwen", token="")

    app.dependency_overrides[get_current_user] = lambda: mock_user
    app.dependency_overrides[get_storage_service] = lambda: mock_storage
    app.dependency_overrides[get_qwen_service] = lambda: qwen_service_no_token

    try:
        response = client.post(
            "/api/analyze",
            json={
                "image_path": VALID_IMAGE_PATH,
                "query": "Analyze image with missing token",
            },
            headers={"Authorization": "Bearer valid-mock-token"},
        )

        assert response.status_code == 500
        assert "HF_TOKEN" in response.json()["detail"]
    finally:
        app.dependency_overrides.clear()


# ---------------------------------------------------------------------------
# 5. Qwen upstream failure -> 502 Bad Gateway
# ---------------------------------------------------------------------------
def test_qwen_upstream_failure_returns_502(mock_user, mock_storage, mock_qwen):
    from fastapi import HTTPException
    mock_qwen.analyze.side_effect = HTTPException(
        status_code=502, detail="Upstream Qwen Gradio service encountered an error"
    )

    app.dependency_overrides[get_current_user] = lambda: mock_user
    app.dependency_overrides[get_storage_service] = lambda: mock_storage
    app.dependency_overrides[get_qwen_service] = lambda: mock_qwen

    try:
        response = client.post(
            "/api/analyze",
            json={
                "image_path": VALID_IMAGE_PATH,
                "query": "Analyze image with failing Qwen",
            },
            headers={"Authorization": "Bearer valid-mock-token"},
        )

        assert response.status_code == 502
        assert "Upstream" in response.json()["detail"]
    finally:
        app.dependency_overrides.clear()


def test_qwen_upstream_failure_uses_local_fallback(mock_user, mock_storage):
    qwen_service = QwenService(space="AdityaSingh1531/qwen", token="test-token")
    qwen_service._client = MagicMock()
    qwen_service._client.predict.side_effect = RuntimeError("upstream AppError")

    app.dependency_overrides[get_current_user] = lambda: mock_user
    app.dependency_overrides[get_storage_service] = lambda: mock_storage
    app.dependency_overrides[get_qwen_service] = lambda: qwen_service

    try:
        response = client.post(
            "/api/analyze",
            json={
                "image_path": VALID_IMAGE_PATH,
                "query": "Analyze image while upstream is unavailable",
            },
            headers={"Authorization": "Bearer valid-mock-token"},
        )

        assert response.status_code == 200
        assert "AKASHA Earth Observation" in response.json()["answer"]
    finally:
        app.dependency_overrides.clear()


# ---------------------------------------------------------------------------
# 6. Signed URL is NEVER returned in response
# ---------------------------------------------------------------------------
def test_signed_url_never_returned_to_client(mock_user, mock_storage, mock_qwen):
    app.dependency_overrides[get_current_user] = lambda: mock_user
    app.dependency_overrides[get_storage_service] = lambda: mock_storage
    app.dependency_overrides[get_qwen_service] = lambda: mock_qwen

    try:
        response = client.post(
            "/api/analyze",
            json={
                "image_path": VALID_IMAGE_PATH,
                "query": "Analyze and test URL leakage",
            },
            headers={"Authorization": "Bearer valid-mock-token"},
        )

        assert response.status_code == 200
        raw_response_text = response.text
        # Ensure signed URL substring does not appear anywhere in the response body
        assert SAMPLE_SIGNED_URL not in raw_response_text
        assert "storage.googleapis.com" not in raw_response_text
        assert "secret-token-uuid" not in raw_response_text
        assert list(response.json().keys()) == ["answer"]
    finally:
        app.dependency_overrides.clear()


# ---------------------------------------------------------------------------
# 7. Signed URL is NEVER written to logs
# ---------------------------------------------------------------------------
def test_signed_url_and_secret_never_logged(mock_user, mock_storage, mock_qwen, caplog):
    app.dependency_overrides[get_current_user] = lambda: mock_user
    app.dependency_overrides[get_storage_service] = lambda: mock_storage
    app.dependency_overrides[get_qwen_service] = lambda: mock_qwen

    caplog.set_level(logging.DEBUG)

    try:
        response = client.post(
            "/api/analyze",
            json={
                "image_path": VALID_IMAGE_PATH,
                "query": "Check logs for secrets",
            },
            headers={"Authorization": "Bearer valid-mock-token"},
        )

        assert response.status_code == 200
        all_logs = caplog.text
        # Ensure neither the signed URL nor its signature components appear in logs
        assert SAMPLE_SIGNED_URL not in all_logs
        assert "secret-token-uuid" not in all_logs
        # Verify safe structured logs were emitted
        assert "Qwen request started for image_path=" in all_logs
        assert "Calling Qwen Space" in all_logs
        assert "Qwen request completed" in all_logs
    finally:
        app.dependency_overrides.clear()


# ---------------------------------------------------------------------------
# 8. Qwen receives the exact signed URL generated by backend
# ---------------------------------------------------------------------------
def test_qwen_receives_exact_signed_url(mock_user, mock_storage, mock_qwen):
    app.dependency_overrides[get_current_user] = lambda: mock_user
    app.dependency_overrides[get_storage_service] = lambda: mock_storage
    app.dependency_overrides[get_qwen_service] = lambda: mock_qwen

    try:
        response = client.post(
            "/api/analyze",
            json={
                "image_path": VALID_IMAGE_PATH,
                "query": "Test exact URL contract",
                "max_new_tokens": 128,
            },
            headers={"Authorization": "Bearer valid-mock-token"},
        )

        assert response.status_code == 200
        # Assert Qwen was invoked with the exact signed URL from backend
        mock_qwen.analyze.assert_called_once()
        call_kwargs = mock_qwen.analyze.call_args[1]
        assert call_kwargs["image_url"] == SAMPLE_SIGNED_URL
        assert call_kwargs["max_new_tokens"] == 128
    finally:
        app.dependency_overrides.clear()


# ---------------------------------------------------------------------------
# 9. Authentication checks (401 when missing or invalid)
# ---------------------------------------------------------------------------
def test_missing_authentication_returns_401():
    # Call without Authorization header
    response = client.post(
        "/api/analyze",
        json={
            "image_path": VALID_IMAGE_PATH,
            "query": "Analyze without credentials",
        },
    )
    assert response.status_code == 401
    assert "Authentication credentials were not provided" in response.json()["detail"]


def test_invalid_token_returns_401():
    with patch("api.routes.verify_firebase_token") as mock_verify:
        from fastapi import HTTPException
        mock_verify.side_effect = HTTPException(status_code=401, detail="Invalid token")

        response = client.post(
            "/api/analyze",
            json={
                "image_path": VALID_IMAGE_PATH,
                "query": "Analyze with bad token",
            },
            headers={"Authorization": "Bearer invalid-token"},
        )
        assert response.status_code == 401


# ---------------------------------------------------------------------------
# 10. Path validation & Traversal rejection (400)
# ---------------------------------------------------------------------------
def test_path_traversal_returns_400(mock_user):
    # Test path traversal with real FirebaseStorageService path validator
    real_storage = FirebaseStorageService()
    app.dependency_overrides[get_current_user] = lambda: mock_user
    app.dependency_overrides[get_storage_service] = lambda: real_storage

    try:
        response = client.post(
            "/api/analyze",
            json={
                "image_path": f"satellite_images/{TEST_USER_ID}/../../../etc/passwd.png",
                "query": "Malicious path attempt",
            },
            headers={"Authorization": "Bearer valid-mock-token"},
        )
        assert response.status_code == 400
        assert "directory traversal" in response.json()["detail"].lower()
    finally:
        app.dependency_overrides.clear()


# ---------------------------------------------------------------------------
# 11. max_new_tokens validation (422)
# ---------------------------------------------------------------------------
def test_max_new_tokens_out_of_range_returns_422(mock_user):
    app.dependency_overrides[get_current_user] = lambda: mock_user

    try:
        # Test lower than 16
        response_too_low = client.post(
            "/api/analyze",
            json={
                "image_path": VALID_IMAGE_PATH,
                "query": "Tokens too low",
                "max_new_tokens": 5,
            },
            headers={"Authorization": "Bearer valid-mock-token"},
        )
        assert response_too_low.status_code == 422

        # Test higher than 2048
        response_too_high = client.post(
            "/api/analyze",
            json={
                "image_path": VALID_IMAGE_PATH,
                "query": "Tokens too high",
                "max_new_tokens": 5000,
            },
            headers={"Authorization": "Bearer valid-mock-token"},
        )
        assert response_too_high.status_code == 422
    finally:
        app.dependency_overrides.clear()


# ---------------------------------------------------------------------------
# 12. Health check endpoint (lightweight, no model inference)
# ---------------------------------------------------------------------------
def test_status_endpoint():
    response = client.get("/api/status")
    assert response.status_code == 200
    data = response.json()
    assert data["status"] == "AKASHA API running"
    assert "qwen_configured" in data
    assert "firebase_configured" in data
    assert "version" in data
